import Head from "next/head";
import App from "../components/App/App";
import { GlobalStoreProvider } from "../components/GlobalStore/globalStore";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Strava Report Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalStoreProvider>
        <App/>
      </GlobalStoreProvider>
    </div>
  );
}
